feat: Basic UI for restaurantListView
code-sherpas/food-to-go-client pull request #3
Opened 2022-01-01 11:35 UTC by ashikka

2022-01-21 14:45 UTC, gornovah requested changes

2022-01-21 14:45 UTC, gornovah commented on api/carouselData.ts
> +
Hi @ashikka , here we are not respecting the contract we have on the card, we should follow the same way we use to get a restaurant view(response.ts)

2022-01-21 14:45 UTC, gornovah commented on api/carouselData.ts
> +
Think that you simulate the contract response here, but we need to simulate the fetch of the backend URL that returns the contract with a API call

2022-01-21 14:45 UTC, gornovah commented on api/listRestaurantViewResponse.ts
> +}
@ashikka can you check the contract?, it does not correspond to the one we have on the card.

2022-01-21 14:45 UTC, gornovah commented on views/listOfRestaurantView.tsx
>  export default function ListofRestaurantView() {
ListOfRestaurantView

2022-01-21 14:45 UTC, gornovah commented on views/restaurantView.tsx
> +    // opacity: 0.9,
if we dont need this, can we remove?

2022-01-21 14:45 UTC, gornovah commented on App.tsx
>        {/* <ListofRestaurantView/> */}
Why it is commented?

2022-01-21 14:45 UTC, gornovah commented on components/CarouselItem.tsx
> +const CarouselItem = ({ item, index }: { item: Item, index: number }) => {
CarouselItem.tsx ->Why is the name of this file in capital letters and the others in small letters?

2022-01-21 14:45 UTC, gornovah commented on api/listRestaurantViewResponse.ts
> +                distance: "307 m",
Can you read this?

2022-01-24 12:51 UTC, ashikka commented on components/CarouselItem.tsx
> +const CarouselItem = ({ item, index }: { item: Item, index: number }) => {
I have changed

2022-01-24 12:56 UTC, ashikka commented on App.tsx
>        {/* <ListofRestaurantView/> */}
For testing purpose

2022-01-24 14:58 UTC, gornovah commented on App.tsx
>        {/* <ListofRestaurantView/> */}
It is recommended that if it only serves that purpose, it should be removed to keep the code clean.

2022-02-01 11:00 UTC, gornovah commented on api/dealsResponse.ts
> +    data: [{
@ashikka here the contract is not this one, it would have to be the last contract I put in comments. https://code-sherpas.jetbrains.space/im/issue/3eqHXC2labP0?message=3o70003o7&channel=4fMFSp4DjzAL

2022-02-01 11:01 UTC, gornovah commented on api/recommendedResponse.ts
> +    data: [{
The same that the previous comment in dealsResponse.ts

2022-02-01 11:03 UTC, gornovah commented on api/restaurantResponse.ts
> +  data: [{
This should be the view from one restaurant, why we have two restaurants now?

2022-02-01 11:07 UTC, gornovah commented on api/listRestaurantData.json
> +    "data": [
With the change of having the view split in three:

/api/store/deals -> dealsResponse.ts
/api/store/recommended ->recommendedResponse.ts
/api/location/me -> locationResponse.ts

This answer is not needed, is it?

2022-02-01 17:42 UTC, ashikka commented on api/dealsResponse.ts
> +    data: [{
@gornovah I fixed the contact to now be same as the one mentioned on space

2022-02-01 17:43 UTC, ashikka commented on api/recommendedResponse.ts
> +    data: [{
Fixed

2022-02-01 17:47 UTC, ashikka commented on api/restaurantResponse.ts
> +  data: [{
This change was made by mistake, I have reverted it to the single restaurant response now

2022-02-01 17:47 UTC, ashikka commented on api/listRestaurantData.json
> +    "data": [
Yup, I removed the file

2022-02-01 17:47 UTC, ashikka commented
@gornovah I have made the fixes, please review when you can. Thank you!

2022-02-02 09:38 UTC, gornovah approved these changes

2022-02-02 09:39 UTC, merged